### ISSUE TITLE
dialysis registry >> summary >> investigation

### ISSUE THREAD

**Issue by sivapriyacheerla** [ProductBoat/Indian-Renal-Registry#907]
serology  >>serology  status  is not showing in patient summary.
https://www.screencast.com/t/SIo8hAlr5Ey.

**Comment by PhaneendraPB** [comment]
Dialysis patient summary is different compared with other registries. So please ask naveen sir to display it or not.

**Comment by ProductBoat** [comment]
1st issues completed
